# Generated by Django 5.2.8 on 2025-11-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fefu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='last_name',
        ),
    ]
