# Generated by Django 5.2.7 on 2025-11-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fefu_lab', '0002_remove_teacher_faculty_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
