"""Django settings for web_2025 project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

SECRET_KEY = r"|Zpg8A,q*jZXmhDzK`mJ0ay2T1hAION\]Vo;#oONlf6|qgZr)phdFY.$Mh%S6Lh$"

BASE_DIR = Path(__file__).resolve().parent.parent

ENV = os.environ.get("DJANGO_ENV", "development").lower()
IS_DEVELOPMENT = ENV == "development"
IS_PRODUCTION = ENV == "production"

DEBUG = not IS_PRODUCTION

# Database

if IS_DEVELOPMENT:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": os.environ.get("DJANGO_POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("DJANGO_POSTGRES_PORT", "5432"),
            "USER": os.environ.get("DJANGO_POSTGRES_USER", "fefu-lab"),
            "PASSWORD": os.environ.get("DJANGO_POSTGRES_PASSWORD", "E1i26ZFa4b5L8UdE"),
            "NAME": os.environ.get("DJANGO_POSTGRES_NAME", "fefu-lab"),
        },
    }

# Apps

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fefu_lab.apps.FefuLabConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Security

if IS_DEVELOPMENT:
    ALLOWED_HOSTS = ["*"]
    CSRF_TRUSTED_ORIGINS = ["http://*"]
else:
    allowed_host = os.environ.get("DJANGO_ALLOWED_HOST", "*").lower()
    ALLOWED_HOSTS = [
        # Нужен для HEALTHCHECK проверок. Лучше переписал бы так, чтобы была CLI утилита
        # или HTTP ручка на /health. Причина - желание избежать использования
        # внешних утилит, таких как curl, которые вносят угрозы безопасности.
        "localhost",
        allowed_host,
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        f"http://{allowed_host}",
    ]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

AUTHENTICATION_BACKENDS = [
    "fefu_lab.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Session

SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Internationalization

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Asia/Vladivostok"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# Path consts

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/profile/"
LOGOUT_REDIRECT_URL = "/"

# Other consts

ROOT_URLCONF = "web_2025.urls"
WSGI_APPLICATION = "web_2025.wsgi.application"
ASGI_APPLICATION = "web_2025.asgi.application"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
